# Generated by Django 3.1.5 on 2021-03-28 18:44

from django.db import migrations, models
import music.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(blank=True, default=None, max_length=40, verbose_name='Исполнитель')),
                ('album', models.CharField(blank=True, default=None, max_length=40, verbose_name='Альбом')),
                ('song', models.CharField(blank=True, default=None, max_length=100, verbose_name='Композиция')),
                ('media_file', models.FileField(upload_to=music.models.get_upload_to)),
            ],
        ),
    ]
