# Generated by Django 3.1.5 on 2021-03-26 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disk', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormModel',
        ),
    ]
